{"name": "Проверка логина курьера в системе с невалидными login и password", "status": "passed", "description": "BUG: на вторые тестовые данные приходит JSONDecodeError", "steps": [{"name": "Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 12346, 'password': 123456}"}], "start": 1710008488403, "stop": 1710008488651}, {"name": "Получаем статус код", "status": "passed", "start": 1710008488651, "stop": 1710008488651}], "parameters": [{"name": "payload", "value": "{'login': 12346, 'password': 123456}"}], "start": 1710008488397, "stop": 1710008488651, "uuid": "ad561610-7ea7-4dfe-a345-7c52fa97fc6b", "historyId": "331d9432710b06f1873ce75cbdfac4db", "testCaseId": "3985f711d4af10eb604b2f695d923949", "fullName": "tests.test_courier.test_login_courier.TestLoginCourier#test_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests.test_courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MBP-MacbookPro"}, {"name": "thread", "value": "5607-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier.test_login_courier"}]}